### ISSUE TITLE
An attempt has been made to start a new process before the current process has finished its bootstrapping phase. Seems like a bug.

### ISSUE THREAD

**Issue by GiddaZhang** [ChenLiu-1996/CitationMap#7]
Code
- filename is `run.py`
- anaconda environment name is `scholarly`

```
from citation_map import generate_citation_map

# This is my Google Scholar ID. Replace this with your ID.
scholar_id = '***********'
generate_citation_map(scholar_id)
```

The terminal will keep returning the error below for many times. Also, just before the error, the output says something like author profile found, start downloading with a progress bar. Thanks for your help!

Terminal Output:
```
Author profile found, with 3 publications.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/***/github/citation-map/run.py", line 5, in <module>
    generate_citation_map(scholar_id)
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/site-packages/citation_map/citation_map.py", line 287, in generate_citation_map
    author_paper_institution_tuple_list = find_all_citing_institutions(author_profile['publications'],
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/site-packages/citation_map/citation_map.py", line 34, in find_all_citing_institutions
    with Pool(processes=num_processes) as pool:
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/opt/anaconda3/envs/scholarly/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by GiddaZhang** [comment]
update: setting `num_processes=1` seems to solve the problem.

**Comment by ChenLiu-1996** [comment]
Duplicate of #4

**Comment by ChenLiu-1996** [comment]
@GiddaZhang `num_processes=1` will make the script very slow. You can take a look at Issue #4.

**Comment by ChenLiu-1996** [comment]
https://github.com/ChenLiu-1996/CitationMap/issues/4#issuecomment-2258858972

I looked into this issue again.

It seems that, at least on my side, protecting your main function with if __name__ == '__main__' suffices. Like the following:

```
from citation_map import generate_citation_map

if __name__ == '__main__':
    # This is my Google Scholar ID. Replace this with your ID.
    scholar_id = '3rDjnykAAAAJ'
    generate_citation_map(scholar_id)
```

I have updated the README.

**Comment by GiddaZhang** [comment]
I see, it successfully addressed the issue, thx!
