### ISSUE TITLE
Failed to fetch the Google Scholar page

### ISSUE THREAD

**Issue by JunMa11** [ChenLiu-1996/CitationMap#9]
Dear @ChenLiu-1996 ,

Thanks for sharing the amazing tool!

I got the following error when creating the map:

```bash
Finding citing authors and papers on your 51 publications:   0%|                                                                                                        | 0/51 [00:04<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/jma/anaconda3/envs/citemap/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/jma/anaconda3/envs/citemap/lib/python3.10/site-packages/citation_map/citation_map.py", line 199, in __citing_authors_and_papers_from_publication
    citing_authors_and_citing_papers = get_citing_author_ids_and_citing_papers(citing_paper_search_url)
  File "/Users/jma/anaconda3/envs/citemap/lib/python3.10/site-packages/citation_map/scholarly_support.py", line 31, in get_citing_author_ids_and_citing_papers
    raise Exception('Failed to fetch the Google Scholar page')
Exception: Failed to fetch the Google Scholar page
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jma/anaconda3/envs/citemap/lib/python3.10/site-packages/citation_map/citation_map.py", line 287, in generate_citation_map
    author_paper_institution_tuple_list = find_all_citing_institutions(author_profile['publications'],
  File "/Users/jma/anaconda3/envs/citemap/lib/python3.10/site-packages/citation_map/citation_map.py", line 57, in find_all_citing_institutions
    all_citing_author_paper_info_nested = list(tqdm(pool.imap(__citing_authors_and_papers_from_publication, all_publication_info),
  File "/Users/jma/anaconda3/envs/citemap/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/Users/jma/anaconda3/envs/citemap/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
Exception: Failed to fetch the Google Scholar page
```

Here is the code to reproduce the error:

```python
from citation_map import generate_citation_map
scholar_id = 'bW1UV4IAAAAJ'
generate_citation_map(scholar_id)
```

Any suggestions are highly appreciated. 

Thanks again for sharing the amazing tool!

Best regards,
Jun

**Comment by ChenLiu-1996** [comment]
Two things:

1. As per the updated Readme, it is recommended to protect your main function with `if __name__ == '__main__'` to avoid multiprocessing errors. Like the following:
```
from citation_map import generate_citation_map

if __name__ == '__main__':
    scholar_id = 'bW1UV4IAAAAJ'
    generate_citation_map(scholar_id)
```

2. The error you encountered is likely the first problem in the [Debug section](https://github.com/ChenLiu-1996/CitationMap/tree/main?tab=readme-ov-file#debug). You can take a look and see if that helps.
